studentsdb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .settings import MEDIA_ROOT, DEBUG
from students.views.students import StudentDeleteView
from students.views.groups import GroupAddView, GroupUpdateView, GroupDeleteView, groups_list
from students.views.journal import JournalView
from stud_auth.views import ProfileUpdateView, profile_page, users_list

from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from django.views.generic.base import RedirectView, TemplateView


urlpatterns = [
	# Students urls
	url(r'^$', 'students.views.students.students_list', name='home'),
    url(r'^students/add/$', 'students.views.students.students_add', name='students_add'),
    url(r'^students/(?P<pk>\d+)/edit/$', 'students.views.students.students_edit', name='students_edit'),
    url(r'^students/(?P<pk>\d+)/delete/$', StudentDeleteView.as_view(), name='students_delete'),
    
    # Groups urls
    url(r'^groups/$', login_required(groups_list), name='groups'),
    url(r'^groups/add/$', login_required(GroupAddView.as_view()), name='groups_add'),
    url(r'^groups/(?P<pk>\d+)/edit/$', login_required(GroupUpdateView.as_view()), name='groups_edit'),
    url(r'^groups/(?P<pk>\d+)/delete/$', login_required(GroupDeleteView.as_view()), name='groups_delete'),
    
    url(r'^admin/', include(admin.site.urls)),

    # Contact Admin Form
    url(r'^contact-admin/$', 'students.views.contact_admin.contact_admin', name='contact_admin'),
    # Journal Page
    url(r'^journal/(?P<pk>\d+)?/?$', login_required(JournalView.as_view()), name='journal'),

    # User Related urls
    url(r'^users/profile/$', login_required(TemplateView.as_view(template_name='registration/profile.html')), name='profile'),
    url(r'^users/profile/(?P<pk>\d+)/$', login_required(profile_page), name='profile_page'),
    url(r'^users/users_list/$',login_required(users_list), name='users_list'),
    url(r'^users/(?P<pk>\d+)/edit_profile/$', login_required(ProfileUpdateView.as_view()), name='edit_profile'),
    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 'home'},
        name='auth_logout'),
    url(r'^register/complete/$', RedirectView.as_view(pattern_name='home'),
        name='registration_complete'),
    url(r'^users/', include('registration.backends.simple.urls',
        namespace='users')),

    # Social Auth Related urls
    url('^social/', include('social.apps.django_app.urls', namespace='social')),
]

if DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': MEDIA_ROOT})
    ]

js_info_dict = {
    'packages': ('my.package',),
}

urlpatterns += [
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
]

students/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Student(models.Model):
	"""Student Model"""

	class Meta(object):
		verbose_name = u"Студент"
		verbose_name_plural = u"Студенти"

	first_name = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u"Ім'я")

	last_name = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u"Прізвище")

	middle_name = models.CharField(
		max_length=256,
		blank=True,
		verbose_name=u"По-батькові",
		default='')

	birthday = models.DateField(
		blank=False,
		verbose_name=u"Дата народження",
		default='')

	photo = models.ImageField(
		blank=True,
		verbose_name=u"Фото",
		null=True)

	ticket = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u"Білет")

	notes = models.TextField(
		blank=True,
		verbose_name=u"Додаткові нотатки")

	student_group = models.ForeignKey('Group',
		verbose_name=u"Група",
		blank=False,
		null=True,
		on_delete=models.PROTECT)

	def __unicode__(self):
		return u"%s %s" % (self.first_name, self.last_name)

class Group(models.Model):
	"""Group Model"""

	class Meta(object):
		verbose_name = u"Група"
		verbose_name_plural = u"Групи"

	title = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=u"Назва")

	leader = models.OneToOneField('Student',
		verbose_name=u"Староста",
		blank=True,
		null=True,
		on_delete=models.SET_NULL)

	notes = models.TextField(
		blank=True,
		verbose_name=u"Додаткові нотатки")

	def __unicode__(self):
		if self.leader:
			return u"%s (%s %s)" % (self.title, self.leader.first_name, self.leader.last_name)
		else:
			return u"%s" % (self.title,)

students/models/group.py
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models

# Create your models here.
class Group(models.Model):
	"""Group Model"""

	class Meta(object):
		verbose_name = _(u"Group")
		verbose_name_plural = _(u"Groups")

	title = models.CharField(
		max_length=256,
		blank=False,
		verbose_name=_(u"Title"))

	leader = models.OneToOneField('Student',
		verbose_name=_(u"Leader"),
		blank=True,
		null=True,
		on_delete=models.SET_NULL)

	notes = models.TextField(
		blank=True,
		verbose_name=_(u"Notes"))

	def __unicode__(self):
		if self.leader:
			return u"%s (%s %s)" % (self.title, self.leader.first_name, self.leader.last_name)
		else:
			return u"%s" % (self.title,)

students/models/monthjournal.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class MonthJournal(models.Model):
	""" Student Monthly Journal """

	class Meta:
		verbose_name = _(u"Monthly Journal")
		verbose_name_plural = _(u"Monthly Journals")

	student = models.ForeignKey('Student',
		verbose_name=_(u"Student"),
		blank=False,
		unique_for_month='date')

	# we only need year and month, so always set day to first day of the month
	date = models.DateField(
		verbose_name=_(u"Date"),
		blank=False)

	# list of days, each says whether student was presene or not
	present_day1 = models.BooleanField(default=False)
	present_day2 = models.BooleanField(default=False)
	present_day3 = models.BooleanField(default=False)
	present_day4 = models.BooleanField(default=False)
	present_day5 = models.BooleanField(default=False)
	present_day6 = models.BooleanField(default=False)
	present_day7 = models.BooleanField(default=False)
	present_day8 = models.BooleanField(default=False)
	present_day9 = models.BooleanField(default=False)
	present_day10 = models.BooleanField(default=False)
	present_day11 = models.BooleanField(default=False)
	present_day12 = models.BooleanField(default=False)
	present_day13 = models.BooleanField(default=False)
	present_day14 = models.BooleanField(default=False)
	present_day15 = models.BooleanField(default=False)
	present_day16 = models.BooleanField(default=False)
	present_day17 = models.BooleanField(default=False)
	present_day18 = models.BooleanField(default=False)
	present_day19 = models.BooleanField(default=False)
	present_day20 = models.BooleanField(default=False)
	present_day21 = models.BooleanField(default=False)
	present_day22 = models.BooleanField(default=False)
	present_day23 = models.BooleanField(default=False)
	present_day24 = models.BooleanField(default=False)
	present_day25 = models.BooleanField(default=False)
	present_day26 = models.BooleanField(default=False)
	present_day27 = models.BooleanField(default=False)
	present_day28 = models.BooleanField(default=False)
	present_day29 = models.BooleanField(default=False)
	present_day30 = models.BooleanField(default=False)
	present_day31 = models.BooleanField(default=False)

	def __unicode__(self):
		return u'%s: %d, %d' % (self.student.last_name, self.date.month, self.date.year)
	

students/views/contact_admin.py
import logging

from django.shortcuts import render
from django import forms
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.utils.translation import ugettext_lazy

from django.contrib.auth.decorators import permission_required

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from studentsdb.settings import ADMIN_EMAIL

from django.conf import settings

class ContactForm(forms.Form):

	def __init__(self, *args, **kwargs):
		# call original initializatior
		super(ContactForm, self).__init__(*args, **kwargs)

		# this helper object allows us to customize form
		self.helper = FormHelper()

		# form tag attributes
		self.helper.form_class = 'form-horizontal'
		self.helper.form_method = 'post'
		self.helper.form_action = reverse('contact_admin')

		# twitter bootstrap styles
		self.helper.help_text_inline = True
		self.helper.html5_required = True
		self.helper.label_class = 'col-sm-2 control-label'
		self.helper.field_class = 'col-sm-10'

		# form buttons
		self.helper.add_input(Submit('send_button', ugettext_lazy(u"Send")))

	from_email = forms.EmailField(
		label=ugettext_lazy(u"Your e-mail"))

	subject = forms.CharField(
		label=ugettext_lazy(u"Title of the message"),
		max_length=128)

	message = forms.CharField(
		label=ugettext_lazy(u"Message"),
		max_length=2560,
		widget=forms.Textarea)


@permission_required('auth.add_user')
def contact_admin(request):
	# check if form was posted
	if request.method == 'POST':
		# create a form instanse and populate it with data from the request:
		form = ContactForm(request.POST)

		# check whether user data is valid:
		if form.is_valid():
			# send email
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			from_email = form.cleaned_data['from_email']

			try:
				send_mail(subject, message, from_email, [ADMIN_EMAIL])
			except Exception:
				message = _(u"There was an error on the server. Please, try again a bit later.")
				logger = logging.getLogger(__name__)
				logger.exception(message)
			else:
				message = _(u"Message was sended successfully")

			# redirect to same contact page with success message
			return HttpResponseRedirect(
                u'%s?status_message=%s' % (reverse('contact_admin'), message))

	# if there was not POS render blank form
	else:
		form = ContactForm()

	return render(request, 'contact_admin/form.html', {'form': form})
	

students/views/groups.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms import ModelForm
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic import CreateView, UpdateView, DeleteView
from django.utils.translation import ugettext as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import FormActions

from ..models.group import Group
from ..util import paginate

def groups_list(request):
    groups = Group.objects.all().order_by('title')

    # try to order students list
    order_by = request.GET.get('order_by', '')
    if order_by in ('title', 'leader'):
        groups = groups.order_by(order_by)
        if request.GET.get('reverse', '') == '1':
            groups = groups.reverse()

    #paginate groups
    context = paginate(groups, 3, request, {}, var_name="groups")
    
    return render(request, 'students/groups_list.html', context)
    

class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = "__all__"    

    def __init__(self, *args, **kwargs):
        super(GroupForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)

        # add form or edit form
        if kwargs['instance'] is None:
            add_form = True
        else:
            add_form = False

        # set form tag attributes
        if add_form:
            self.helper.form_action = reverse('groups_add')
        else:
            self.helper.form_action = reverse('groups_edit',
                kwargs={'pk': kwargs['instance'].id})
        self.helper.form_method = 'POST'
        self.helper.form_class = 'form-horizontal'

        # set form field properties
        self.helper.help_text_inline = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10'

        # add buttons
        if add_form:
            submit = Submit('add_button', _(u"Add"),
                css_class="btn btn-primary")
        else:
            submit = Submit('save_button', _(u"Save"),
                css_class="btn btn-primary")
        self.helper.layout[-1] = FormActions(
            submit,
            Submit('cancel_button', _(u"Cancel"), css_class="btn btn-link"),
        )

class BaseGroupFormView(object):

    def get_success_url(self):
        return u'%s?status_message=%s' \
            % (reverse('groups'), _(u"Changes saved successfully"))

    def post(self, request, *args, **kwargs):
        # handle cancel button
        if request.POST.get('cancel_button'):
            return HttpResponseRedirect(reverse('groups') +
                u'?status_message=%s' % _(u"Changes were canceled"))
        else:
            return super(BaseGroupFormView, self).post(
                request, *args, **kwargs)

class GroupAddView(BaseGroupFormView, CreateView):
    model = Group
    form_class = GroupForm
    template_name = 'students/groups_form.html' 

class GroupUpdateView(BaseGroupFormView, UpdateView):
    model = Group
    form_class = GroupForm
    template_name = 'students/groups_form.html'

class GroupDeleteView(BaseGroupFormView, DeleteView):
    model = Group
    template_name = 'students/groups_confirm_delete.html'

students/views/journal.py
from datetime import datetime, date
from dateutil.relativedelta import relativedelta
from calendar import monthrange, weekday, day_abbr
from django.http import JsonResponse

from django.core.urlresolvers import reverse
from django.views.generic.base import TemplateView

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from ..models.student import Student
from ..models.monthjournal import MonthJournal
from ..util import paginate, get_current_group


class JournalView(TemplateView):
	template_name = 'students/journal.html'    

	def get_context_data(self, **kwargs):
		# get context data grom TemplateView class
		context = super(JournalView, self).get_context_data(**kwargs)

		# check if we need to display some cpecific month
		if self.request.GET.get('month'):
			month = datetime.strptime(self.request.GET['month'], '%Y-%m-%d'
				).date()
		else:
			# otherwise just displaying current month data
			today = datetime.today()
			month = date(today.year, today.month, 1)

		# calculate current, previous and next month details;
		# we need this for month navigation element in template
		next_month = month + relativedelta(months=1)
		prev_month = month - relativedelta(months=1)
		context['prev_month'] = prev_month.strftime('%Y-%m-%d')
		context['next_month'] = next_month.strftime('%Y-%m-%d')
		context['year'] = month.year
		context['month_verbose'] = month.strftime('%B')

		# we'll use this variable in students pagination
		context['cur_month'] = month.strftime('%Y-%m-%d')
		
		# prepare variable for template to generate
		# journal table header elements
		myear, mmonth = month.year, month.month
		number_of_days = monthrange(myear, mmonth)[1]
		context['month_header'] = [{'day': d,
			'verbose': day_abbr[weekday(myear, mmonth, d)][:3]}
			for d in range(1, number_of_days+1)]

		# get all students from database, or just one if we need to
		# display journal for one student
		if kwargs.get('pk'):
			queryset = [Student.objects.get(pk=kwargs['pk'])]
		else:
			current_group = get_current_group(self.request)
			if current_group:
				queryset = Student.objects.filter(student_group=current_group).order_by('last_name')
			else:
				queryset = Student.objects.all().order_by('last_name')

		# url to update student presence, for form post
		update_url = reverse('journal')

		# for all students and get data need
		students = []
		for student in queryset:
			# try to get journal object by month selected
			# month and current student
			try:
				journal = MonthJournal.objects.get(student=student, date=month)
			except Exception:
				journal = None
			days = []
			for day in range(1, 31):
				days.append({
					'day': day,
					'present': journal and getattr(journal, 'present_day%d' % day, False) or False,
					'date': date(myear, mmonth, day).strftime('%Y-%m-%d')
					})

			# push all data of student
			students.append({
				'fullname': u'%s %s' % (student.last_name, student.first_name),
				'days': days,
				'id': student.id,
				'update_url': update_url,
				})

		# apply pagination to student's list
		context = paginate(students, 10, self.request, context,
			var_name='students')

		# return updated list of data
		return context

	def post(self, request, *args, **kwargs):
		data = request.POST

		# prepare student, dates and presence data
		current_date = datetime.strptime(data['date'], '%Y-%m-%d').date()
		month = date(current_date.year, current_date.month, 1)
		present = data['present'] and True or False
		student = Student.objects.get(pk=data['pk'])

		# get or create journal object for given student and month
		journal = MonthJournal.objects.get_or_create(student=student, date=month)[0]

		# set new presence or journal for given student and save result
		setattr(journal, 'present_day%d' % current_date.day, present)
		journal.save()

		# return success status
		return JsonResponse({'status': 'success', 'key': 'success'})

students/templates/students/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang='uk'>
  
  <head>
    <meta charset="UTF-8"/>
    <title>{% trans "Students Accounting Service" %} - {% block meta_title %}{% endblock meta_title %}</title>
    <meta name="description"
          value="Система Обліку Студентів Навчального Закладу" />

    <!-- Include Styles -->
	<link rel="stylesheet"
		  href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/css/bootstrap-datetimepicker.min.css">
	<link rel="stylesheet" href="{{ PORTAL_URL }}{% static 'css/main.css' %}">

	{% block extra_css %}{% endblock extra_css %}

  </head>

  <body>
    <!-- Start Container -->
    <div class="container">

      <!-- Start Header -->
      <div class="row" id="header">

        <!-- Logo -->
        <div class="col-xs-6">
          <h1>{% trans "Students Accounting Service" %}</h1>
        </div>

        {% if user.is_authenticated %}
        <!-- Groups Selector -->
        <div class="col-xs-4" id="group-selector">
          <strong>{% trans "Group:" %}</strong>
          <select>
            <option value="">{% trans "All Students" %}</option>
            {% for group in GROUPS %}
            <option value="{{ group.id }}"{% if group.selected %}selected="1"{% endif %}>{{ group.title }}{% if group.leader %}, {{ group.leader }}{% endif %}
            </option>
            {% endfor %}
          </select>
        </div>
        <!-- User's toolbar for authenticated users -->
        <div class="col-xs-2" id="user-toolbar">
          <a class="log_text" href="{% url "profile" %}">{{ user.get_full_name|default:user.username }}</a> |
          <a class="log_text" href="{% url "users:auth_logout" %}">{% trans "Logout" %}</a>
        </div>

        {% else %}

        <!-- User's toolbar for anonymous users -->
        <div class="col-xs-6" id="user-toolbar">
          <a class="icon_log" href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">
            <img height="20" width="20" src="{% static "img/facebook.jpg" %}">
          </a> |
          <a class="log_text" href="{% url "users:auth_login" %}">{% trans "Login" %}</a> |
          <a class="log_text" href="{% url "users:registration_register" %}">{% trans "Register" %}</a>
        </div>
        {% endif %}
      </div>
      <!-- End Header -->

      <!-- Start SubHeader -->
      <div class="row" id="sub-header">
        <div class="col-xs-10">
          <ul class="nav nav-tabs" role="tablist">
		      <li id='students_page' role="presentation" {% if request.path == '/' %} class="active" {% endif %}><a href="{% url 'home' %}">{% trans "Students" %}</a></li>
		      
          {% if user.is_authenticated %}
          <li role="presentation" {% if '/journal' in request.path %} class="active" {% endif %}><a href="/journal">{% trans "Journal" %}</a></li>
		      <li role="presentation" {% if '/groups' in request.path %} class="active" {% endif %}><a href="{% url 'groups' %}">{% trans "Groups" %}</a></li>
          {% endif %}

          {% if perms.auth.add_user %}
          <li role="presentation" {% if '/contact-admin' in request.path %} class="active" {% endif %}><a href="{% url "contact_admin" %}">{% trans "Contact" %}</a></li>
          {% endif %}

		      </ul>
        </div>
        <div class="col-xs-2" id="languages">
          <input type="image" width="30" height="20" src="{% static "img/usa.jpg" %}" value="en" class="language_check">
          <input type="image" width="30" height="20" src="{% static "img/ua.png" %}" value="uk" class="language_check">
        </div>
      <!-- End SubHeader -->

      <!-- Start Content Colums -->
      <div class="row" id="content-colums">
        <div class="col-xs-12" id="content-column">
          <div id="loading">
          </div>
          {% block status_message %}
          {% if request.GET.status_message %}
          <div class="alert alert-warning" role="alert">{{ request.GET.status_message }}</div>
          {% endif %}
          {% endblock %}

          <h2>{% block title %}{% endblock title %}</h2>
          {% block content %}{% endblock content %}
        </div>
      </div>
      <!-- End Content Colums -->

      <!-- Start Footer -->
      <div class="row" id="footer">
        <div class="col-xs-12">
          &copy; 2016 {% trans "Students Accounting Service" %}
        </div>
      </div>
      <!-- End Footer -->

      <!-- Modal Boilerplate -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
           aria-labelledby="myModalLAbel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"
                      aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel"><!-- --></h4>
            </div>
            <div class="modal-body"><!-- --></div>
            <div class="modal-footer"><!-- --></div>
          </div>
        </div>
      </div>

    <!-- Javascripts Section -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
  <script src="{% static "js/jquery.cookie.js" %}"></script>
	<script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/js/bootstrap-datetimepicker.min.js"></script>
  <script type="text/javascript" src="{% url 'django.views.i18n.javascript_catalog' %}"></script>
  <script src="{% static "js/main.js" %}"></script>
	{% block extra_js %}{% endblock extra_js %}
  </body>

</html>

students/templates/students/groups_confirm_delete.html
{% extends "students/base.html" %}

{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block meta_title %}{% trans "Delete Group" %}{% endblock meta_title %}

{% block status_message %}
  {% if form.errors %}
  <div class="alert alert-warning" role="alert">
    {% trans "Please, fix this error" %}
  </div>
  {% endif %}
{% endblock status_message %}

{% block title %}{% trans "Delete Group" %}{% endblock title %}

{% block content %}

<form action="{% url "groups_delete" group.id %}" method="post">
  {% csrf_token %}
  <p>{% blocktrans %}Do you really want to delete group: "{{ group }}"?{% endblocktrans %}</p>
  <input type="submit" value="{% trans "Yes" %}" name="delete_button"
  		 class="btn btn-danger" />
  <a href="{% url "groups" %}" class="btn btn-info">{% trans "No" %}</a> 
  <br /> <br />
</form>
{% endblock content %}

students/templates/students/groups_form.html
{% extends "students/base.html" %}

{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block meta_title %}{% trans "Group's Form" %}{% endblock meta_title %}

{% block status_message %}
  {% if form.errors %}
  <div class="alert alert-warning" role="alert">
    {% trans "Please, fix this errors" %}
  </div>
  {% endif %}
{% endblock status_message %}

{% block title %}{% trans "Group's Form" %}{% endblock title %}

{% block content %}

{% crispy form %}

{% endblock content %}

students/templates/students/groups_list.html
{% extends "students/base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block meta_title %}{% trans "Groups List" %}{% endblock meta_title %}

{% block title %}{% trans "Groups List" %}{% endblock title %}

{% block content %}
	{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
		  {% if groups %}
          <!-- Add Student Button -->
          <a class="btn btn-primary" href="{% url 'groups_add' %}">{% trans "Add Group" %}</a>

          <!-- Start Students Listing -->
		  <table class="table table-hover table-striped">
		  
		    <thead>
			  <tr>
				<th> <a href="">№</a></th>
				<th> 
				  <a href="{% url "groups" %}?order_by=title{% if request.GET.order_by == 'title' and request.GET.reverse != '1' %}&amp;reverse=1{% endif %}">
					Назва
					{% if order_by == 'title' and reverse != '1' %}&uarr;
					{% elif order_by == 'title' and reverse == '1' %}&darr;
					{% endif %}
				  </a>
				</th>
				<th>
				  <a href="{% url "groups" %}?order_by=leader{% if request.GET.order_by == 'leader' and request.GET.reverse != '1' %}&amp;reverse=1{% endif %}">
				    {% trans "Leader" %}
				    {% if order_by == 'leader' and reverse != '1' %}&uarr;
					{% elif order_by == 'leader' and reverse == '1' %}&darr;
					{% endif %}
				  </a>
				</th>
				<th> {% trans "Actions" %}</th>
			  </tr>
			</thead>
			<tbody>
			  {% for group in groups %}
			    <tr>
				  <td>{{ forloop.counter }}</td>
				  <td> <a href="{% url "groups_edit" group.id %}">{{ group.title }}</a></td>
				  <td> {% if group.leader %}<a href="{% url "students_edit" group.leader.id %}">{{ group.leader.last_name }} {{ group.leader.first_name }}</a>{% else %}{% trans "None" %}{% endif %}</td>
				  <td>
				    <div class="dropdown">
				      <button class="btn btn-default dropdown-toggle"
				    		  type="button" data-toggle="dropdown">{% trans "Action" %}
				        <span class="caret"></span>
				      </button>
				      <ul class="dropdown-menu" role="menu"> 
				        <li><a href="{% url "groups_edit" group.id %}">{% trans "Edit" %}</a></li>
                        <li><a href="{% url "groups_delete" group.id %}">{% trans "Delete" %}</a></li>
				      </ul>
				    </div>
				  </td>
			    </tr>
			  {% endfor %}
			</tbody>
		  </table>
		  {% else %}
		  <p>{% trans "Groups are not found until in database." %}</p>
		  {% endif %}
		  {% with object_list=groups %}
  			{% include "students/pagination.html" %}
  		  {% endwith %}
	{% endwith %}
		  <!-- End Students Listing -->
{% endblock content %}

students/templates/students/student_list.html
{% extends "students/base.html" %}

{% load staticfiles %}

{% block meta_title %}Студенти{% endblock meta_title %}

{% block title %}База Студентів{% endblock title %}

{% block content %}
         
	<h2></h2>
	<ul>
		{% for student in object_list %}
			<li>{{ student.last_name }}</li>
		{% endfor %}
	</ul>

{% endblock content %}